USE WAREHOUSE COMPUTE_WH;
USE DATABASE REFERRAL_TRIAGE;
USE SCHEMA PUBLIC;

-- These are just for testing purposes for synthetic data, once we figure out how to pipe data from S3 to snowflake, we can just use real time data. 
CREATE FILE FORMAT IF NOT EXISTS JSON_STANDARD TYPE = JSON;
CREATE STAGE IF NOT EXISTS FORMAT_A_JSON_STAGE FILE_FORMAT = JSON_STANDARD;
CREATE STAGE IF NOT EXISTS FORMAT_B_JSON_STAGE FILE_FORMAT = JSON_STANDARD;

COPY INTO RAW_FORMAT_A_REFERRALS (raw) FROM @FORMAT_A_JSON_STAGE FILE_FORMAT = JSON_STANDARD ON_ERROR = 'CONTINUE';
COPY INTO RAW_FORMAT_B_REFERRALS (raw) FROM @FORMAT_B_JSON_STAGE FILE_FORMAT = JSON_STANDARD ON_ERROR = 'CONTINUE';

SELECT COUNT(*) FROM RAW_FORMAT_A_REFERRALS;
SELECT COUNT(*) FROM RAW_FORMAT_B_REFERRALS;
SELECT * FROM RAW_FORMAT_A_REFERRALS LIMIT 3;


