"""
Exports the AI triage results from Snowflake into a file the web UI can read.

Pipeline position:
    GP referral -> Jev (urgency) -> Claude Haiku (justification + next step)
    -> Snowflake (AI_REFERRAL_RESULTS) -> THIS SCRIPT -> ui/data/referrals.js -> ui/index.html

Run it on its own with:
    .venv/bin/python export_ui.py
It is also called automatically at the end of main.py, so the UI data is refreshed
every time the pipeline processes new referrals.
"""

import json
import os
from datetime import datetime, timezone
from decimal import Decimal

from snowflake.connector import DictCursor

from db import get_connection

OUTPUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ui", "data", "referrals.js")

# The connector returns VARIANT columns as JSON strings, so these are parsed back into dicts
# before export; otherwise the UI would receive JSON-inside-a-string.
VARIANT_COLUMNS = {"probabilities", "justification"}

# Written at the top of every referrals.js. Kept here because hand edits to that file are
# overwritten on each export.
DATA_FILE_HEADER = """\
// AUTO-GENERATED by export_ui.py. Do not edit by hand; changes are overwritten on every export.
//
// Contains every row of OUTPUT_UI.PUBLIC.REFERRAL_TRIAGE_VIEW, i.e. each standardised GP referral
// joined to its AI result (Jev urgency + confidence + probabilities, Claude justification +
// recommendation). Referrals not yet processed by the pipeline have null AI fields.
//
// It is loaded by ui/index.html via a <script> tag and read by ui/app.js as window.REFERRAL_DATA.
// Shape: { generated_at: "<ISO timestamp>", referrals: [ { referral_id, nhi_number, ... }, ... ] }
//
// Contains patient information (NHI numbers, conditions). It is git-ignored; do not commit it
// or upload it anywhere public.
"""


def normalise_row(row):
    """Lowercases Snowflake's upper-case column names and converts values to plain JSON types."""
    result = {}
    for key, value in row.items():
        key = key.lower()
        if key in VARIANT_COLUMNS and isinstance(value, str):
            value = json.loads(value)
        elif isinstance(value, Decimal):
            # NUMBER columns come back as Decimal, which json can't serialise.
            value = float(value)
        result[key] = value
    return result


def fetch_triage_view():
    """Reads every row of the triage view from Snowflake and returns them as a list of dicts."""
    conn = get_connection()
    cursor = conn.cursor(DictCursor)
    # The view LEFT JOINs referrals to AI results, so unprocessed referrals are included too
    # (with empty AI columns) and show up in the UI's "Awaiting AI triage" tab.
    cursor.execute("SELECT * FROM OUTPUT_UI.PUBLIC.REFERRAL_TRIAGE_VIEW")
    rows = cursor.fetchall()
    cursor.close()
    conn.close()
    return [normalise_row(r) for r in rows]


def export_ui_data(path=OUTPUT_PATH):
    """Writes the triage view to the data file the UI reads. Returns the number of referrals written."""
    referrals = fetch_triage_view()

    # default=str stringifies values json can't handle natively, e.g. the processed_at timestamp.
    payload = json.dumps(
        {"generated_at": datetime.now(timezone.utc).isoformat(), "referrals": referrals},
        indent=2,
        default=str,
    )

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(DATA_FILE_HEADER)
        f.write(f"window.REFERRAL_DATA = {payload};\n")

    return len(referrals)


if __name__ == "__main__":
    count = export_ui_data()
    print(f"Exported {count} referrals to {OUTPUT_PATH}")
