CREATE ROLE IF NOT EXISTS DATA_ENGINEER_ROLE;
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS VIEWER_ROLE;

GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON INTEGRATION s3_integration TO ROLE data_engineer_role;

-- Analysts can read everything, but shouldn't modify raw tables
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE REFERRAL_TRIAGE TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA REFERRAL_TRIAGE.PUBLIC TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA REFERRAL_TRIAGE.PUBLIC TO ROLE ANALYST_ROLE;
GRANT SELECT ON VIEW V_TRIAGE_QUEUE TO ROLE ANALYST_ROLE;
GRANT SELECT ON VIEW V_WORKFORCE_CAPACITY TO ROLE ANALYST_ROLE;
GRANT SELECT ON VIEW V_PATIENT_REVIEW_QUEUE TO ROLE ANALYST_ROLE;
GRANT SELECT, UPDATE ON TABLE PATIENTS TO ROLE ANALYST_ROLE;  -- if analysts also act as coordinators

-- Viewers (dashboard) only see curated views, not raw tables
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE VIEWER_ROLE;
GRANT USAGE ON DATABASE REFERRAL_TRIAGE TO ROLE VIEWER_ROLE;
GRANT USAGE ON SCHEMA REFERRAL_TRIAGE.PUBLIC TO ROLE VIEWER_ROLE;
GRANT SELECT ON VIEW V_TRIAGE_QUEUE TO ROLE VIEWER_ROLE;
GRANT SELECT ON VIEW V_WORKFORCE_CAPACITY TO ROLE VIEWER_ROLE;

-- We will create profiles for each member tomorrow to run on the same database 
-- Example code for creating USER
CREATE USER IF NOT EXISTS 
    PASSWORD = 'TemporaryPassword123!'
    DEFAULT_ROLE = ANALYST_ROLE
    MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE ANALYST_ROLE TO USER xxx;


