-- CREATE ROLES
CREATE ROLE IF NOT EXISTS DATA_ENGINEER_ROLE;
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS VIEWER_ROLE;

-- DATA ENGINEER ROLE
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON DATABASE REFERRAL_TRIAGE TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA REFERRAL_TRIAGE.PUBLIC TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA REFERRAL_TRIAGE.PUBLIC TO ROLE DATA_ENGINEER_ROLE;
GRANT CREATE TABLE ON SCHEMA REFERRAL_TRIAGE.PUBLIC TO ROLE DATA_ENGINEER_ROLE;
GRANT CREATE STAGE ON SCHEMA REFERRAL_TRIAGE.PUBLIC TO ROLE DATA_ENGINEER_ROLE;
GRANT CREATE PIPE ON SCHEMA REFERRAL_TRIAGE.PUBLIC TO ROLE DATA_ENGINEER_ROLE;
GRANT CREATE VIEW ON SCHEMA REFERRAL_TRIAGE.PUBLIC TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON DATABASE OUTPUT_UI TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA OUTPUT_UI.PUBLIC TO ROLE DATA_ENGINEER_ROLE;
GRANT CREATE VIEW ON SCHEMA OUTPUT_UI.PUBLIC TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON TABLE OUTPUT_UI.PUBLIC.AI_REFERRAL_RESULTS TO ROLE DATA_ENGINEER_ROLE;

-- ANALYST ROLE
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE REFERRAL_TRIAGE TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA REFERRAL_TRIAGE.PUBLIC TO ROLE ANALYST_ROLE;
GRANT SELECT ON TABLE REFERRAL_TRIAGE.PUBLIC.STANDARDIZED_REFERRALS TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE OUTPUT_UI TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA OUTPUT_UI.PUBLIC TO ROLE ANALYST_ROLE;
GRANT SELECT, INSERT ON TABLE OUTPUT_UI.PUBLIC.AI_REFERRAL_RESULTS TO ROLE ANALYST_ROLE;
GRANT SELECT ON VIEW OUTPUT_UI.PUBLIC.REFERRAL_TRIAGE_VIEW TO ROLE ANALYST_ROLE;

-- VIEWER ROLE
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE VIEWER_ROLE;
GRANT USAGE ON DATABASE OUTPUT_UI TO ROLE VIEWER_ROLE;
GRANT USAGE ON SCHEMA OUTPUT_UI.PUBLIC TO ROLE VIEWER_ROLE;
GRANT SELECT ON VIEW OUTPUT_UI.PUBLIC.REFERRAL_TRIAGE_VIEW TO ROLE VIEWER_ROLE;

-- AI PIPELINE SERVICE ACCOUNT
CREATE USER IF NOT EXISTS AI_PIPELINE_SVC 
    PASSWORD = 'PIPELINE_SVC' 
    DEFAULT_ROLE = ANALYST_ROLE 
    DEFAULT_WAREHOUSE = COMPUTE_WH MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE ANALYST_ROLE TO USER AI_PIPELINE_SVC;

-- EXAMPLE ANALYST USER
-- CREATE USER IF NOT EXISTS XXX 
--  PASSWORD = 'TemporaryPassword123!' 
--  DEFAULT_ROLE = ANALYST_ROLE 
--  DEFAULT_WAREHOUSE = COMPUTE_WH 
--  MUST_CHANGE_PASSWORD = TRUE;
--GRANT ROLE ANALYST_ROLE TO USER XXX;

-- EXAMPLE VIEWER USER
-- CREATE USER IF NOT EXISTS DASHBOARD_USER 
--  PASSWORD = 'TemporaryPassword123!' 
--  DEFAULT_ROLE = VIEWER_ROLE 
--  DEFAULT_WAREHOUSE = COMPUTE_WH 
--  MUST_CHANGE_PASSWORD = TRUE;
--GRANT ROLE VIEWER_ROLE TO USER DASHBOARD_USER;
