CREATE USER IF NOT EXISTS AI_PIPELINE_SVC
    PASSWORD = 'PIPELINE_SVC'
    DEFAULT_ROLE = ANALYST_ROLE
    MUST_CHANGE_PASSWORD = FALSE;  -- FALSE since it's a service account, not a human logging in

GRANT ROLE ANALYST_ROLE TO USER AI_PIPELINE_SVC;
GRANT USAGE ON DATABASE OUTPUT_UI TO ROLE ANALYST_ROLE;
GRANT ALL ON SCHEMA OUTPUT_UI.PUBLIC TO ROLE ANALYST_ROLE;
GRANT INSERT, SELECT ON TABLE OUTPUT_UI.PUBLIC.AI_REFERRAL_RESULTS TO ROLE ANALYST_ROLE;
GRANT SELECT ON TABLE REFERRAL_TRIAGE.PUBLIC.STANDARDIZED_REFERRALS TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE REFERRAL_TRIAGE TO ROLE ANALYST_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_ROLE;

GRANT USAGE ON DATABASE REFERRAL_TRIAGE TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA REFERRAL_TRIAGE.PUBLIC TO ROLE ANALYST_ROLE;
GRANT SELECT ON TABLE REFERRAL_TRIAGE.PUBLIC.STANDARDIZED_REFERRALS TO ROLE ANALYST_ROLE;

GRANT USAGE ON DATABASE OUTPUT_UI TO ROLE ANALYST_ROLE;
GRANT ALL ON SCHEMA OUTPUT_UI.PUBLIC TO ROLE ANALYST_ROLE;
GRANT INSERT, SELECT ON TABLE OUTPUT_UI.PUBLIC.AI_REFERRAL_RESULTS TO ROLE ANALYST_ROLE;


